server:
  port: 9999
  servlet:
    session:
      timeout: 30
person:
  name: zhangsan
  age: 18
info:
  url: www.baidu.com
  msg: testUrl
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xz_test?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: 123456
    initialSize: 10
    maxActive: 20
    minIdle: 1
    maxWait: 60000
mybatis:
  mapper-locations: classpath:mappers/*.xml
demo:
  log:
    path: ./logs
    level: INFO